### ISSUE TITLE
check_rgw errors

### ISSUE THREAD

**Issue by DerDanilo** [ceph/ceph-nagios-plugins#67]
1st Problem:
There is no support for the `--keyfile` switch. All other check support it. Please add the keyfile switch.

2nd Problem:

When running the check with simple options, if fails while trying to fetch mon config:
```
./check_ceph_rgw --id nagios -c /etc/ceph/ceph.conf
RGW ERROR:  :: failed to fetch mon config (--no-mon-config to skip)
```

The option doesn't seem to be supported by the script though:
```
 ./check_ceph_rgw --id nagios --no-mon-config
usage: check_ceph_rgw [-h] [-d] [-B] [-e EXE] [-c CONF] [-i ID] [-n NAME] [-V]
check_ceph_rgw: error: unrecognized arguments: --no-mon-config
```

What to do to check RGW Gateway status?

**Comment by valerytschopp** [comment]
You can use [check_ceph_rgw_api](the https://github.com/ceph/ceph-nagios-plugins#check_ceph_rgw_api) instead.
You should define a radosgw user **nagios** with the capability `buckets=read`, and use its access and secret keys to query the admin API.

Nagios user:
```sh
# create nagios user in radosgw
radosgw-admin user create --uid nagios --display_name "Nagios checker" --email nagios@example.com
# set the capability
radosgw-admin caps add --uid nagios --caps "buckets=read" 
# get the access_key and secret_key
radosgw-admin user info --uid nagios
```
