### ISSUE TITLE
check_ceph_df checks only first class

### ISSUE THREAD

**Issue by niekosau** [ceph/ceph-nagios-plugins#73]
Hi,

i've discovered that check_ceph_df uses only 3rd line from ceph df output to report usage ignoring other classes.

For example my ceph df output is as following:
```
RAW STORAGE:
    CLASS     SIZE        AVAIL       USED        RAW USED     %RAW USED
    hdd       115 TiB      50 TiB      64 TiB       65 TiB         56.56
    ssd        13 TiB     8.8 TiB     4.1 TiB      4.3 TiB         32.63
    TOTAL     128 TiB      59 TiB      68 TiB       69 TiB         54.10
```
and check reports only:
```
RAW usage 56.56%
```

ceph version:
`ceph version 14.2.16`

**Comment by valerytschopp** [comment]
Hi @niekosau 

Unfortunately the `check_ceph_df` parses text output, and it is very prone to error. 

The check have to be fully rewritten to parse json (from `ceph df -f json`) and not the `ceph df` text output anymore.

Any help refactoring the `check_ceph_df` check is very welcome.
